kind: Service
apiVersion: v1
metadata:
  name: terraform-service
spec:
  type: NodePort
  selector:
    app: terraform
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30001