apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-http
  namespace: default
  labels:
    app: java-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http
  template:
    metadata:
      labels:
        app: java-http
    spec:
      containers:
        - name: java-http
          image: sergomyaso/java-http
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1
              memory: 20Mi
